export const AUTH_STATE = {
  ANONYMOUS: 'ANONYMOUS',
  LOGGED_IN: 'LOGGED_IN',
  AWAITING_AUTH_RESPONSE: 'AWAITING_AUTH_RESPONSE'
};

export const AUTH_ACTION_TYPE = {
  ATTEMPTING_LOGIN: 'AUTH/ATTEMPTING_LOGIN',
  LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
  LOGIN_FAILED: 'AUTH/LOGIN_FAILED',
  ATTEMPTING_LOGOUT: 'AUTH/ATTEMPTING_LOGOUT',
  LOGOUT_SUCCESS: 'AUTH/LOGOUT_SUCCESS',
  LOGOUT_FAILED: 'AUTH/LOGOUT_FAILED'
};

export const NOTE_ACTION_TYPE = {
  SET_NOTES: 'NOTE/SET_NOTES',
  ADD_NOTE: 'NOTE/ADD_NOTE',
  UPDATE_NOTE: 'NOTE/UPDATE_NOTE',
  REMOVE_NOTE: 'NOTE/REMOVE_NOTE'
};
